export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

// maybe consistent names? :D
export const CLIPBOARD_LOADED_ALL = 'CLIPBOARD_LOADED_ALL';
export const CLIPBOARD_LOADED_ALL_LABELS = 'CLIPBOARD_LOADED_ALL_LABELS'
export const CLIPBOARD_UPDATED = 'CLIPBOARD_UPDATED';
export const CLIPBOARD_CREATED = 'CLIPBOARD_CREATED';
export const CLIPBOARD_REMOVED = 'CLIPBOARD_REMOVED';

export const CLIPBOARD_LABEL_ADDED = 'CLIPBOARD_LABEL_ADDED'
export const CLIPBOARD_LABEL_REMOVED = 'CLIPBOARD_LABEL_REMOVED'

export const CLIPBOARD_ITEM_UPDATED = 'CLIPBOARD_ITEM_UPDATED'
export const CLIPBOARD_ITEM_ADDED = 'CLIPBOARD_ITEM_ADDED'
export const CLIPBOARD_ITEM_REMOVED = 'CLIPBOARD_ITEM_REMOVED'

export const SHOPPING_LIST_LOADED_ALL = 'SHOPPING_LIST_LOADED_ALL';
export const SHOPPING_LIST_UPDATED = 'SHOPPING_LIST_UPDATED';
export const SHOPPING_LIST_CREATED = 'SHOPPING_LIST_CREATED';
export const SHOPPING_LIST_REMOVED = 'SHOPPING_LIST_REMOVED';

export const SHOPPING_LIST_ITEM_UPDATED = 'SHOPPING_LIST_ITEM_UPDATED'
export const SHOPPING_LIST_ITEM_ADDED = 'SHOPPING_LIST_ITEM_ADDED'
export const SHOPPING_LIST_ITEM_REMOVED = 'SHOPPING_LIST_ITEM_REMOVED'
