export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const CLIPBOARD_LOADED_ALL = 'CLIPBOARD_LOADED_ALL';
export const CLIPBOARD_LOADED_ALL_LABELS = 'CLIPBOARD_LOADED_ALL_LABELS'