export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const CLIPBOARD_LOADED_ALL = 'CLIPBOARD_LOADED_ALL';
export const CLIPBOARD_LOADED_ALL_LABELS = 'CLIPBOARD_LOADED_ALL_LABELS'

export const CLIPBOARD_ITEM_UPDATED = 'CLIPBOARD_ITEM_UPDATED'
export const CLIPBOARD_ITEM_ADDED = 'CLIPBOARD_ITEM_ADDED'
export const CLIPBOARD_ITEM_REMOVED = 'CLIPBOARD_ITEM_REMOVED'